### ISSUE TITLE
White page with Mattermost 5.12

### ISSUE THREAD

**Issue by jicka** [mattermost/mattermost-plugin-autotranslate#14]
Hello,

Thank you for developing the plugin. After updating Mattermost to version 5.12 (from 5.10), I have noticed that the Autotranslate plugin has an issue, that turns the whole page white.
I know you have published new commits recently, but I cannot read code to know if this fixes this issue. Please ignore this if it has already been fixed and only needs to be released. 
Mattermost 5.11 and 5.12 introduced the following changes for plugins (from https://docs.mattermost.com/administration/changelog.html#release-v5-12-feature-release):
- If your plugin uses the DeleteEphemeralMessage plugin API, update it to accept a postId string parameter.

Again, thank you for this great plugin.

If I can help in any way about the issue, please ask.

Jonas

**Comment by saturninoabril** [comment]
You're welcome @jicka 👍 

Yup, it's fixed by https://github.com/mattermost/mattermost-plugin-autotranslate/commit/8d149c417290800e0c9e236f9e8a8e370eab346d.  I'll try to cut a new release using such commit.

Note that the recent [dependency update](https://github.com/mattermost/mattermost-plugin-autotranslate/commit/da91d5e0175f4f17c7abbd54255f20287b242d97) breaks the plugin in case you'll build it on master at the moment.  I'd be happy if you're interested in fixing the master 😄, please let me know.  If not, no worries since I'm planning to fix it, hopefully this week.

**Comment by jicka** [comment]
Hello @saturninoabril ,thanks for taking the time to let me know! I am not a developer and only dabble in code, so I will not be able to help you at the moment. However, I plan to learn to contribute over the summer :)
Have a nice day!
Jonas
